### ISSUE TITLE
stringz symbol table

### ISSUE THREAD

**Issue by jplanck** [WChargin/lc3web#3]
The symbol table is not correctly incremented when a stringz is used.

```
 .orig x3000
```

lbl   add r1,r2,r3
txt  .stringz "hello"
lbl2  add r1,r2,r3
     .end

creates the code
0x  Label   Hex     Instruction
    x3000   lbl x1283   ADD R1, R2, R3
    x3001   txt x0068   NOP
    x3002   lbl2    x0065   NOP
    x3003       x006C   NOP
    x3004       x006C   NOP
    x3005       x006F   NOP
    x3006       x0000   NOP
    x3007       x1283   ADD R1, R2, R3

the label lbl2 is associated with the second character of stringz instead of line x3007

**Comment by wchargin** [comment]
Confirmed, thanks. I'll fix this.

**Comment by wchargin** [comment]
I wasn't handling assembly directives properly when in their lowercase forms. Thanks very much for reporting! Let me know if any similar issues crop up.

**Comment by jplanck** [comment]
Thanks. I appreciate the quick response.  I'm teaching 225 this quarter and I prefer this one to the windows version for my students.

Regards,

John Planck

**Comment by wchargin** [comment]
Awesome! Glad to hear it :smile:
