### ISSUE TITLE
unable to download symbol table or object file

### ISSUE THREAD

**Issue by jplanck** [WChargin/lc3web#6]
Once Assembled, The download symbol table and download object file buttons have no affect in firefox.  Works in chrome.

Browser: Firefox 45.0.2
OS windows10.

One of my assignments has the students using the symbol table.

Thanks

**Comment by wchargin** [comment]
Interesting. It looks like firefox doesn't support the `download=` attribute on `<a>`nchor tags, or at least programmable clicks thence, even though it's listed in MDN. This limitation is limited in a few StackOverflow threads as well.

An alternative would be to use a `Blob` to download the files:

``` javascript
var data = '\x30\x00\x00\x48\x00\x65\x00\x79\x00\x00'
// ^ result of .ORIG x3000; .STRINGZ "Hey"; .END
var blob = new Blob([data], {type: 'application/octet-stream'});
var url = URL.createObjectURL(blob);
window.location = url; // ← best way to do this?
```

I'll look into this. Want to make sure it doesn't break Chrome! :smile:

In the short term, of course, using Chrome is a workaround.

**Comment by wchargin** [comment]
@jplanck I've pushed what I think is a fix! Would you mind visiting http://wchargin.github.io/lc3web/#blob-download (note the added hash target) and seeing if this works for you? If it breaks anything in either browser, let me know and I'll revert it.

**Comment by jplanck** [comment]
It works in both chrome and firefox.  There is no dialog, so you get a random characters as the filename.

thanks,

john

**Comment by wchargin** [comment]
Yep, I know about the random characters. (This is discussed in the comments in 851953afcab43ec803ca0646d1be922d59ee7d14.) I haven't figured out a way to avoid this.

Chrome and Firefox each let me rename the file in a "Save File" dialog, though. Maybe that's because I have "Ask me where to save each file before downloading" checked.
