### ISSUE TITLE
.blkw can only write values in binary, not decimal

### ISSUE THREAD

**Issue by DanCRichards** [WChargin/lc3web#7]
The standard LC3 simulator can take Integers after
.blkw 

This isn't too much of an error, but caused my code to not assemble when attempted it with your system

**Comment by wchargin** [comment]
Thanks for reporting!

Write `#1234` instead of `1234`:
```
.orig x3000
.fill x1234
.blkw #10
.fill x5678
.end
```

The specification is ambiguous on what the correct behavior is ([see p. 145 here](http://users.ece.utexas.edu/~patt/07s.360N/handouts/360n_ch07.pdf)), so I take the convention that the hash must be used everywhere for consistency.
