### ISSUE TITLE
Pressing <Enter> in the search bar should trigger search

### ISSUE THREAD

**Issue by DanCRichards** [WChargin/lc3web#8]
If you search for an Address such as 0x3000 and then run your code, after such the search field doesn't work when you attempt to go into the field and press enter to search for 0x3000 again. You need to delete what you wrote, and try again.

**Comment by wchargin** [comment]
This is more of a feature request than a bug—the search field updates on every keystroke, and pressing enter never does anything.

That said, I'm happy to make pressing enter perform the search again.

**Comment by wchargin** [comment]
@DanCRichards: if I understood your request correctly, this should now be implemented. (Refresh, maybe clear your cache.) Feel free to reopen if this doesn't resolve your issue.
