### ISSUE TITLE
Clear all registers

### ISSUE THREAD

**Issue by skhillon** [WChargin/lc3web#9]
Could you please add a button to set all registers (including GPRs, Saved.USP, and Saved.SSP) to 0? Otherwise I have to reload the page and assemble all files again.

**Comment by wchargin** [comment]
Sure. I'll try to do this tomorrow. Feel free to ping me if I forget about it.

**Comment by wchargin** [comment]
(Note, by the way, that you can always just click a register value to edit it. Clicking each of the eight registers and setting them to zero is a bit annoying, but easier than refreshing and assembling everything again.)

**Comment by wchargin** [comment]
I've added two buttons: "Clear R0–R7" and "Reset all registers" (to their defaults). Let me know if this isn't sufficient or if you find any problems.

**Comment by skhillon** [comment]
Hi William,

I tested out the feature and I'm not sure if the registers are clearing. Is it possible that they clear behind-the-scenes and the text on-screen just doesn't update?

Here's a screen recording: https://www.youtube.com/watch?v=CSKthq_OGpI

**Comment by wchargin** [comment]
Thanks for the clear video. Could you clear your cache and refresh? I suspect that your browser is using a cached version of the core code.

If this doesn't fix the issue, could you please let me know (a) whether there are any messages in the JavaScript console, and (b) what OS version and browser version you're using?

**Comment by skhillon** [comment]
Yup, that fixed it :)
